"""Assemble the section outputs into a Word document programmatically.

No template file is used: the docx is built from scratch so this stays a
pure-Python paper-companion app (no .docx asset to keep in version control).
If you want a polished template fill-in, port this output into your own
trial unit's SAP template.
"""

from __future__ import annotations

from datetime import date
from io import BytesIO
from typing import TYPE_CHECKING

from docx import Document
from docx.shared import Pt

if TYPE_CHECKING:
    from .pipeline import SAPDraft


def build_sap_docx(draft: "SAPDraft", model_label: str) -> bytes:
    """Render a SAPDraft into a .docx file and return its bytes."""

    doc = Document()

    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    title = doc.add_heading("Statistical Analysis Plan (Draft)", level=0)
    title.alignment = 1  # WD_ALIGN_PARAGRAPH.CENTER

    sub = doc.add_paragraph()
    sub.alignment = 1
    run = sub.add_run(
        f"Generated by SAPAI Open on {date.today().isoformat()} using {model_label}."
    )
    run.italic = True

    notice = doc.add_paragraph()
    notice.alignment = 1
    notice_run = notice.add_run(
        "This is an AI-generated first draft. It must be reviewed by a "
        "qualified trial statistician before any use in a live trial."
    )
    notice_run.italic = True
    notice_run.font.size = Pt(9)

    doc.add_paragraph()

    for section in draft.section_order:
        content = draft.sections.get(section.key, "").strip()
        error = draft.errors.get(section.key)

        doc.add_heading(section.title, level=1)

        if error:
            err_p = doc.add_paragraph()
            err_run = err_p.add_run(f"[Generation failed for this section: {error}]")
            err_run.italic = True
            continue

        if not content:
            empty_p = doc.add_paragraph()
            empty_run = empty_p.add_run("[No content produced for this section.]")
            empty_run.italic = True
            continue

        for para in content.split("\n\n"):
            para = para.rstrip()
            if not para:
                continue
            doc.add_paragraph(para)

    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = 1
    footer_run = footer.add_run(
        "SAPAI Open · King's College London Clinical Trials Unit · "
        "Companion to Jafari et al., medRxiv 2026."
    )
    footer_run.italic = True
    footer_run.font.size = Pt(8)

    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()
